[book]
title = "Rust sokoban"
authors = []
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "./../../build"

[output.html]
google-analytics = "UA-26280927-4"
additional-css = ["custom.css"]
additional-js = ["custom.js"]
git-repository-url = "https://github.com/iolivia/rust-sokoban"
git-repository-icon = "fa-github"
