[book]
title = "Rust编写推箱子游戏教程 "
authors = []
language = "zh"
multilingual = false
src = "src"

[build]
build-dir = "./../../build/zh_CN"

[output.html]
google-analytics = "UA-26280927-4"
additional-css = ["custom.css"]
additional-js = ["custom.js"]
git-repository-url = "https://github.com/iolivia/rust-sokoban"
git-repository-icon = "fa-github"
site-url = "/zh_CN/"
